### ISSUE TITLE
Set Subtitle as "Default"

### ISSUE THREAD

**Issue by pandavova** [skid9000/Crunchyroll-Downloader#10]
Currently its not the Default, so you need to select it everytime.
(You can get the info with MediaInfo)

**Comment by skid9000** [comment]
What do you mean by default ?

**Comment by pandavova** [comment]
When you play a mkv file with a softsub in VLC, it selects the subtitle file itself if its set as default.
Here a screenshot from MediaInfo and a mkv from this downloader:
![1](https://user-images.githubusercontent.com/9296158/39622955-507e24d0-4f94-11e8-8eb7-d8b5ef8a36fe.png)
As you can see, the subtitle is not set as default.

You can set it as default with ffmpeg and "-disposition:s:0 default". 
"s" stands for the subtitle and the "0" is the first subtitle track.

**Comment by skid9000** [comment]
AH, i understand now !
I will see if i can implemant that directly from youtube-dl ('cause it's youtube-dl who use ffmpeg for the conversion)

**Comment by skid9000** [comment]
Merged #12 so it will be in the next release, thanks :)
