### ISSUE TITLE
Program dont open

### ISSUE THREAD

**Issue by renatosk** [skid9000/Crunchyroll-Downloader#13]
Im trying to use the program but he doesnt open , he shows up in seconds on task manager but then vanishes , tried compatibility mode but nothing , i'm on windows 8.1

**Comment by skid9000** [comment]
Please fill at least the issue template.
I can't help you with so few informations :/

**Comment by renatosk** [comment]
#6 Its this same problem

**Comment by skid9000** [comment]
That dosen't help me ...
A issue can be very different on two different env.

**Comment by renatosk** [comment]
**Checklist**

- [yes ] I checked if my issue is already referenced.
- [ yes] I use a release version (from a tag or master branch).
- [ i dont know if this downloaded] Youtube-DL is up to date
- [ yes] I use the version of .NET Framework that is recommended or better

**Describe the bug**
Nothing happens when clicking to open the program

**To Reproduce**
Steps to reproduce the behavior:
1. Click the program
2. nothing happens


**Expected behavior**
it was for the program to open

**Screenshots**


**Desktop (please complete the following information):**
 - OS (from a cmd : winver) :Windows 8.1 6.3 compilation 9600
 - Youtube-DL version  :2018.06.19
 - Crunchyroll-Downloader version: i cant click on the button , but i downloaded the 1.2.6c version

**Comment by skid9000** [comment]
Can you screenshot me the content of this folder ?

C:\ProgramData\Crunchy-DL

**Comment by renatosk** [comment]
I got the program working by deleting the content on C:\ProgramData\Crunchy-DL , now i got the error "Stoped working" when trying to login https://imgur.com/a/2LTqJZX

**Comment by skid9000** [comment]
The login module is missing U_u

Try to download https://download.tucr.tk/login.zip and put it in the folder and then restart the app.

NORMALLY, it SHOULD fix the issue ...

**Comment by renatosk** [comment]
Ok, after 2 attempts the program automatically downloaded the login.zip , now its working fine , thanks for the help
