### ISSUE TITLE
Add an option to download a entire series in one time

### ISSUE THREAD

**Issue by renatosk** [skid9000/Crunchyroll-Downloader#14]
I would like this option to be like , you put the link in URL (exemple:http://www.crunchyroll.com/laid-back-camp) and download all the videos avaliable in the page , for the names of the files you can use the original episodes names.

**Comment by skid9000** [comment]
Thanks for submitting the request.

This is already on the roadmap, will update here if i have news.

**Comment by skid9000** [comment]
Added.
