### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Nixuge** [skid9000/Crunchyroll-Downloader#15]
I can't login to the app :/

**Comment by leonekmi** [comment]
Thanks for reporting your issue. Please fill the issue template :

OS (from a cmd : winver) :

Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version"

Crunchyroll-Downloader version (click on the about button from MainWindow) :

These informations can help us to give you instructions to repair issue.

**Comment by jofeju** [comment]
Same problem, can't login.

OS: Windows 10
Youtube-DL version: 2018.07.29
Crunchyroll-Downloader version: 1.2.6c

**Comment by mefelosc** [comment]
Same problem, can't login. ²

**Comment by skid9000** [comment]
Can you screenshot the content of this folder and send it here ?

C:\ProgramData\Crunchy-DL

**Comment by Nixuge** [comment]
http://prntscr.com/kexcfg
http://prntscr.com/kexci3

**Comment by skid9000** [comment]
Ok so the login module is here …

Can you tell me exactly what you did and tell me here did it go wrong ?

Is the login windows not opening ?
Did the login process crashed ?
Did the login window exited sucessfully but the login button is still clickable ?

**Comment by mefelosc** [comment]
https://imgur.com/8W3qosO.png

**Comment by mefelosc** [comment]
Did the login window exited sucessfully but the login button is still clickable ? Yes.

**Comment by skid9000** [comment]
I got some others feedbacks, it seems that Crunchyroll changed something in their login method ...

I will investigate tomorrow ...

**Comment by skid9000** [comment]
Since the problem is on the login module ==> https://github.com/skid9000/CrunchyrollAuth/issues/1

**Comment by skid9000** [comment]
I probably found what is going on here ...
So unless i found a solution to solve the Cloudflare checks, you have to put a valid cookies.txt in `C:\ProgramData\Crunchy-DL` and it should work.

https://github.com/skid9000/CrunchyrollAuth/issues/1#issuecomment-412377092

**Comment by skid9000** [comment]
I fixed the login module!

A realease that fix this bug will be published this afternoon.

**Comment by skid9000** [comment]
Fixed! Will be on master with the 1.2.7 release soon.
