### ISSUE TITLE
Can't Download "Permission Denied"

### ISSUE THREAD

**Issue by MrRojano97** [skid9000/Crunchyroll-Downloader#17]
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
When I attempt to download Anime with the App, at the end of CMD Screen there is an error.
"file:\\ <route> Permission denied

**To Reproduce**
1. Just try to download any video like http://www.crunchyroll.com/wake-up-girls/episode-13-towards-the-light-749749
2. See error

**Expected behavior**
The download will be start.

**Screenshots**
[https://imgur.com/a/FBraG5Q](https://imgur.com/a/FBraG5Q)

**Desktop:**
 - OS : Windows 10 1803 Compilation (10.0.17134.228)
 - Youtube-DL version: 2018.9.1
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : 1.2.7

**Additional context**
I tried in a Virtual Machine and in the real deal, both with the same Windows 10 Pro x64 version, and with all of the stuff to run the Software.

**Comment by skid9000** [comment]
Does it throw the error right away?

The program is intended to work only on Windows since WPF is not Wine/Mono friendly...

Also do you have write permission on the folder you try to download at?

**Comment by skid9000** [comment]
Ok i successfully reproduced the issue and i probably am a big idiot.
I will try to push a hotfix ASAP.

**Comment by skid9000** [comment]
Ok so i'm a idiot, the fix seems to work on my testing environement now, will push the 1.2.7c ASAP.

**Comment by skid9000** [comment]
Fixed.

**Comment by MrRojano97** [comment]
Thanks! Now works perfectly
