### ISSUE TITLE
Can this be run on Ubuntu

### ISSUE THREAD

**Issue by axipher** [skid9000/Crunchyroll-Downloader#19]
Is there a way to run this under python in Linux (Ubuntu 18.04 in my case, but that shouldn't be super inportant).

**Comment by monoclex** [comment]
install `mono`

**Comment by falfiya** [comment]
No, you can't run this program within python since C# requires the dotnet framework.

**Comment by monoclex** [comment]
you *could* have a hacky workaround where python executes mono which in turn executes the program, but at that point it's pointless.

I'd be nice if this tool could be made with a CLI interface and made with dot net core.

**Comment by skid9000** [comment]
Since i use WPF, i don't think mono could run it.
Still, it's a won't fix.
