### ISSUE TITLE
Allow for resuming downloading a show after the program unexpectedly ends

### ISSUE THREAD

**Issue by axipher** [skid9000/Crunchyroll-Downloader#20]
I have this running in a Windows 10 VM and the VM crashes on episode ~300 or ~350 of Bleach from Crunchyroll.

When I start it back up again, it wants to start from the first episode and ignores the already downloaded episodes.

Could you have it check for the existence of an episode before it tries to re-download it?  Youtube-dl does allow for a "download archive" text file that can keep track of all completed episodes so far.

**Comment by axipher** [comment]
Okay, so looking through the Youtube-dl documentation, I found a workaround for "resuming" downloads.

If you create a text document called "C:\Users\axipher\youtube-dl.conf" and put in the following lines of code, it will then generate a new text file to track the completed episodes and upon re-running Crunchyroll-Downloader, it will respect this archive list.  The key here is they Crunchyroll-Downloader is runnng its own version of youtube-dl in the ProgramData folder so it needs the youtube-dl config file in that location to use it instead of the usual "Roaming" folder in AppData.

youtube-dl.conf
```
--ignore-errors
--continue
--download-archive C:/Users/axipher/youtube-dl_archive.txt
```

Example of the generated text file at "C:\Users\axipher\youtube-dl_archive.txt"
```
crunchyroll 650673
crunchyroll 650675
crunchyroll 650677
crunchyroll 650679
```


So I believe all that is needed is to add "--download-archive C:/Users/axipher/youtube-dl_archive.txt" to the <program.cs> file and/or configure that to use another text field in the Windows UI using {archive_file} or something like that.

I might take a crack at setting up all the required components to download and compile a new branch of this, but Github is totally new to me and I'm learning how it's structured on the fly.

**Comment by skid9000** [comment]
Wew, i didn't think about that...
If i have some time this W.E i will see if i can implement that.

Feel free to open a PR if you want to help ^^

**Comment by axipher** [comment]
I'm sure you can implement something that simple :P

I'll be honest, I don't quite know how the whole Git system works for pull requests and branches and what not.  I'm more then willing to help test stuff and I can browse the code trying to find problems and what not, but no idea how to actually use the site other then cloning and building per the readme.

**Comment by skid9000** [comment]
I pushed the implementation on the develop branch, haven't tested it yet tho.

**Comment by skid9000** [comment]
I don't really have much time to test this feature :/ If someone could confirm if the solution is working then i can merge it to master...
