### ISSUE TITLE
Crunchyroll-Downloader not deleting ffmpeg zip files after installation

### ISSUE THREAD

**Issue by falfiya** [skid9000/Crunchyroll-Downloader#21]
**Checklist**
- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
It's not a bug and it doesn't really matter, it's just that C:\ProgramData\Crunchy-DL\
still contains the .zip files that were downloaded from this github repo.

**To Reproduce**
Install this program

**Expected behavior**
It removes the .zip files

**Screenshots**
![image](https://user-images.githubusercontent.com/22552895/47276559-d31ede80-d56c-11e8-8cc1-e4d0c9f9bcc8.png)

**Desktop (please complete the following information):**
 - OS (from a cmd : winver) : 
![image](https://user-images.githubusercontent.com/22552895/47276567-e8940880-d56c-11e8-869a-ca3ce8ae0746.png)

 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version" 
![image](https://user-images.githubusercontent.com/22552895/47276595-17aa7a00-d56d-11e8-8134-759a0ab1a3db.png)

 - Crunchyroll-Downloader version (click on the about button from MainWindow) : 
![image](https://user-images.githubusercontent.com/22552895/47276613-4294ce00-d56d-11e8-8887-60240175049c.png)

**Comment by falfiya** [comment]
If I've got some free time tomorrow, I'll submit a pull request

**Comment by skid9000** [comment]
Yup, since now if there is a problem in this folder it's completely wiped out, there is no reason to keep theses zip o/
If i have some time this W.E i will fix that.

**Comment by falfiya** [comment]
It doesn't look like I can actually fix this issue. What are you using for the installer?

**Comment by skid9000** [comment]
You can by using the [File.Delete Method](https://docs.microsoft.com/fr-fr/dotnet/api/system.io.file.delete?view=netframework-4.7.2) in MainWindow.xaml.cs

**Comment by falfiya** [comment]
Whoops. Didn't read MainWindow.xaml.cs. My bad.

**Comment by falfiya** [comment]
[I've submitted a pull request](https://github.com/skid9000/Crunchyroll-Downloader/pull/22)

**Comment by falfiya** [comment]
Alright, so just to check with you, use tabs for indentation and try to leave the code style the way it is? I'll submit a pull request to solve **only** this issue.

**Comment by skid9000** [comment]
#24 has been merged to the development branch, thank you for your contribution :)
