### ISSUE TITLE
Compact ffmpeg binary zips with 7z using BZip2 on Ultra

### ISSUE THREAD

**Issue by falfiya** [skid9000/Crunchyroll-Downloader#23]
**Is your feature request related to a problem? Please describe.**
ffmpeg binaries can be compacted.

**Describe the solution you'd like**
Use bz2 with ultra compression.

**Describe alternatives you've considered**
It's not really an issue, it'd just make downloading ffmpeg faster

**Comment by skid9000** [comment]
I don't think it will be as useful as expected, i will see if the difference is worth the work.

**Comment by falfiya** [comment]
It's actually really not. It goes from 20MiB (Current: Deflate) down to about 14.4MiB (LZMA) or 18MiB (BZip2)

**Comment by skid9000** [comment]
Yeah, for 5MiB~ it's a wontfix...
