### ISSUE TITLE
Dependencies seems corrupted or missing

### ISSUE THREAD

**Issue by storm134** [skid9000/Crunchyroll-Downloader#25]
Install release v1.2.7c and NET FrameWork 4.7.1 and Microsoft Visual C++ 2010 Redistributable Package (x86) and NodeJS. but always get the same message "Dependencies seems corrupted or missing, click ok to re-download them" if i click ok  program crashed. amd using windows 7 (64b).

Any Ideas?

**Comment by skid9000** [comment]
Weird, can you give me the details of the app crash ?

**Comment by skid9000** [comment]
Any news ?

**Comment by crackerbad** [comment]
same problem

**Comment by crackerbad** [comment]
> Any news ?

same problem, you can post a complete download link with CrunchyrollAuth and FFMPEG

**Comment by skid9000** [comment]
Are you on Windows 7 too ?

**Comment by crackerbad** [comment]
> Are you on Windows 7 too ?

Yes, Windows 7 Ultimate 64bits

**Comment by skid9000** [comment]
Ok i will try to reproduce it on my Windows 7 vm when i have time.

**Comment by skid9000** [comment]
I successfully reproduced the issue, i will see what i can do...

**Comment by skid9000** [comment]
Ok the issue is kinda weird...
It blocks in the process of downloading youtube-dl...
I use https://yt-dl.org/downloads/latest/youtube-dl.exe to download the latest version of youtube-dl.
However, when you try to access this url in ie (v8) it crashes... But when you try to just access yt-dl.org, it works fine.
So i don't really know what to do ATM...

**Comment by ghost** [comment]
Adding these 2 lines of code in the WebClient block seemed to download the files correctly.
`ServicePointManager.Expect100Continue = true;`
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

**Comment by skid9000** [comment]
Interesting '-'

I will try that on my end this weekend, if it works, will maybe publish a hotfix release.

**Comment by skid9000** [comment]
Ok it seems to work on my side.
I'm going to push the fix on develop.
Thanks @Lugiia ! :)

**Comment by ghost** [comment]
You're welcome :)
