### ISSUE TITLE
Can't download new episode

### ISSUE THREAD

**Issue by Thesinxz** [skid9000/Crunchyroll-Downloader#27]
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x ] Youtube-DL is up to date
- [x ] I use the version of .NET Framework that is recommended or better

**Describe the bug**
when I try to log in, the program load and return to the home screen

**To Reproduce**
1. '...'
2. '....'
3. '....'

**Expected behavior**

**Screenshots**

**Infos (please complete the following information):**
 - OS (from a cmd : winver) :
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version"
 - Crunchyroll-Downloader version (click on the about button from MainWindow) :
 - Region of the Crunchyroll account :
 - URL of what you tried to download :

**Additional context**

**Comment by Thesinxz** [comment]
https://imgur.com/a/xrso2Wq
Now dont make the download

**Comment by Thesinxz** [comment]
i'm trying to download this episode
https://www.crunchyroll.com/kaguya-sama-love-is-war/episode-4-kaguya-wants-affection-the-student-council-wants-it-to-be-said-kaguya-wants-him-to-send-it-miyuki-shirogane-wants-to-talk-781501
i'm premium and can't download this episode

**Comment by skid9000** [comment]
duplicated #26
