### ISSUE TITLE
[Subs] Download EsLa when selecting EsEs.

### ISSUE THREAD

**Issue by guevara15** [skid9000/Crunchyroll-Downloader#28]
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
apart from that I can not download premium videos, when under a non premium or premium video (when I could download it) and I choose the Spanish subtitle language (es-es), I always download it in latin spanish (es-lat)
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/47691290/53196652-d7413280-3618-11e9-9fb1-eaf4b2e9f4b1.png)

![image](https://user-images.githubusercontent.com/47691290/53196250-e07dcf80-3617-11e9-9357-ca0b598d6ab3.png)

**Infos (please complete the following information):**
 - OS (from a cmd : winver) :
![image](https://user-images.githubusercontent.com/47691290/53196276-f2f80900-3617-11e9-8174-bfa1e07f2241.png)
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version"
(2019.02.18)
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : 1.2.7c
 - Region of the Crunchyroll account : Spain (spain)
 - URL of what you tried to download : 
https://www.crunchyroll.com/es/mob-psycho-100/episode-6-poor-lonely-whitey-780925

**Comment by karurosu15** [comment]
the same thing happens to me

**Comment by skid9000** [comment]
Ok it's only a GUI issue.
Until the fix, please use "Español" for EsEs and "Español (España)" for EsLa.
