### ISSUE TITLE
Make this downloading window useful.

### ISSUE THREAD

**Issue by skid9000** [skid9000/Crunchyroll-Downloader#3]
Needed for :

- [ ] The installation of dependencies (in progress)
- [ ] The youtube-dl downloading (need to parse the output of the console)

**Comment by skid9000** [comment]
Started to work on the installation of the deps.
Need to fix async crap and done for that.

On the other hand parsing the output of the youtube-dl console will be a real pain in the ass, if anyone have a idea to do that simply ...

**Comment by skid9000** [comment]
Hum, it seems that InstallAll() is not really working as expected ...

https://github.com/skid9000/Crunchyroll-Downloader/blob/master/Crunchyroll-Downloader/MainWindow.xaml.cs#L122

It dosen't show the download_window and it run every downloading task on a new thread ?
When the function is called, the main thread continue without waiting for the function to finish ...
So at the end, the zip extractor panic 'cause the zip files are not yet downloaded ...

https://puush.tuto-craft.com/907f5W.mp4

**Comment by falfiya** [comment]
Parsing ytdl output is a pain. Maybe something like [edge](https://github.com/tjanczuk/edge) plus [ytdl-core](https://github.com/fent/node-ytdl-core) would do the trick?

**Comment by skid9000** [comment]
I'm not a huge fan of JS honestly, in the end i think i will put the bulk output of yt-dl in the download window, since it is logging crap since the new cloudflare protection anyway...
However that doesn't resolve my problem with the download of dependencies :/

**Comment by skid9000** [comment]
I'm closing this since it will be fixed by the migration to mvvm
