### ISSUE TITLE
Download hardsub videos.

### ISSUE THREAD

**Issue by karurosu15** [skid9000/Crunchyroll-Downloader#37]
Is it possible for the program to create an MP4 video with the subtitle integrated?

**Comment by skid9000** [comment]
youtube-dl can download hardsub videos, but imho the quality is horrible...

If it's only up to me i won't implement it, but if there is really a base of people that need it, welp i will see...

**Comment by skid9000** [comment]
I'm closing this issue, if anybody is interested by this just re-open it.

**Comment by crackerbad** [comment]
This function would be interesting because I use youtube-dl along with media player classic, but I can't choose the crunchyroll subtitle.
Youtube-dl automatically picks the first hardsub
