### ISSUE TITLE
"Something wrong happened while downloading the video. please check your URL or login credentials"

### ISSUE THREAD

**Issue by 123321mario** [skid9000/Crunchyroll-Downloader#38]
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
an error shows up while trying to download

**To Reproduce**
1. login on my account
2. fill the download form
3. press start

**Expected behavior**
the video starts downloading

**Screenshots**
![](https://cdn.discordapp.com/attachments/474130295969284097/573419458601811969/unknown.png)

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : Windows 10 professionnal 32bits ver 1809 17763.437
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version" : 2019.04.30
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : v2.0.0
 - Region of the Crunchyroll account : i tried both FR and US
 - URL of what you tried to download : http://www.crunchyroll.com/fr/yuruyuri/episode-2-tremble-in-fear-686343 (i tried both with and without the /fr/)

**Additional context**
in the credentials page, does i need to enter the email or the username ?

**Comment by skid9000** [comment]
You should use your username when you login.
Also do you have write access on the folder you chooses ? Try to run it as Administrator if you are not sure.

On my side it's working fine so maybe it's a login issue on your side...
Does it throw the error right away when you click on start or does it try to fetch the video info and then it crash ?

**Comment by 123321mario** [comment]
-i used the username
-i ran as admin
-it try to fetch the video before the error shows, I just saw that the app downloaded the .ass file successfuly .

I also tried on another PC with pretty much the same config but the only difference is the windows version is 64bit (the PC where I'm getting errors is 32bit) and it worked perfectly. can this be a problem ?

Sorry for my bad English it's not my native language

**Comment by skid9000** [comment]
Hmm, will test that on a vm in the afternoon but this is weird...

**Comment by skid9000** [comment]
After further testing on multiple environments, i'm unable to reproduce the bug...
It just... works so honestly i don't know :/

**Comment by 123321mario** [comment]
I have another PC where the app works so it's not a big deal fixing it, thanks for trying to help me :)
