### ISSUE TITLE
Download window not working.

### ISSUE THREAD

**Issue by artaeun** [skid9000/Crunchyroll-Downloader#40]
**Checklist**

- [x] I checked if my issue is already referenced.
- [X] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
Stuck at "Fetching video info..." while attempting download.

**To Reproduce**
1. First time install.
2. Login
3. Quality: Best / URL: https://www.crunchyroll.com/the-ancient-magus-bride/episode-1-april-showers-bring-may-flowers-749399 / Subtitles [  ] / Accessible save path chosen.
4.  "Fetching video info..."
5.  Stuck there...

**Expected behavior**
To fetch the video info and start downloading

**Screenshots**
Not necessary

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : Win. 10, Build 1903
 - Youtube-DL version : 2019.05.20
 - Crunchyroll-Downloader version : 2.0.0
 - Region of the Crunchyroll account : Europe? I'm guessing? I'm from Italy 🤷‍♂ 
 - URL of what you tried to download : https://www.crunchyroll.com/the-ancient-magus-bride/episode-1-april-showers-bring-may-flowers-749399

**Comment by skid9000** [comment]
Ok it's because the output from youtube-dl as changed BUT it's downloading, so just wait that it finish and you should be good.

I will try to fix it for v2.1.0

**Comment by artaeun** [comment]
can confirm it does download, now that you mention it. Would it be possible to add, somewhere on the app, the network speed it's running on right now? it would be a good indicator of activity even in case of errors from youtube-dl

**Comment by skid9000** [comment]
The output is completely different so it will be fixed in next version.
Maybe just in case i will put a toggle somewhere to switch in the soft what type of output is expected.
So the "clean" version by default and if toggled the "crappy" ffmpeg version.

**Comment by skid9000** [comment]
Yeah they went back to the crappy ffmpeg version so yup it's not a thing anymore.
