### ISSUE TITLE
Batch-download of series downloads video with non-japanese/non-english single audio track

### ISSUE THREAD

**Issue by artaeun** [skid9000/Crunchyroll-Downloader#41]
**Checklist**

- [x] I checked if my issue is already referenced.
- [X] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**
Batch-download of anime series downloads video files correctly (with "fetching video info...") but the video file has only one audio track in a non-japanese/non-english language (sounds russian, idk)

**To Reproduce**
1. Input of settings after successful login
Quality: Best
URL: https://www.crunchyroll.com/the-ancient-magus-bride
Subtitles [ ]
Accessible save path chosen.

**Expected behavior**
To download batch of files in japanese

**Screenshots**
Not necessary

**Infos:**
 - OS (from a cmd : winver) : Win. 10, Build 1903
 - Youtube-DL version : 2019.05.20
 - Crunchyroll-Downloader version : 2.0.0
 - Region of the Crunchyroll account : Europe? I'm guessing? I'm from Italy 🤷‍♂ 
 - URL of what you tried to download : https://www.crunchyroll.com/the-ancient-magus-bride

**Comment by artaeun** [comment]
![immagine](https://user-images.githubusercontent.com/6439106/58879016-f306ab00-86d4-11e9-9e88-83ce59d69cc2.png)

so i guess it actually goes trough all of them, starting from the bottom (oldest), which makes sense since the only input is a link. So it will probably download the english one as well, but not as a first choice.

**Comment by skid9000** [comment]
Linked to #42
