### ISSUE TITLE
Allow the user to choose what to download from a full-serie link.

### ISSUE THREAD

**Issue by artaeun** [skid9000/Crunchyroll-Downloader#42]
**Is your feature request related to a problem? Please describe.**
If you give the whole series link to the Downloader, it will download everything without looking at the dub language. Besides wasting bandwidth and time, it would just be faster to have a dialog prompt let you choose what to download.

**Describe the solution you'd like**
It would be great to have a dialog prompt to let you choose what to download

**Describe alternatives you've considered**
Adding support for multiple link downloads, so as to paste directly a series of links (aka the single episodes) and let the Downloader do the rest. It can be done one episode at a time, but it's very time consuming.

**Additional context**

it's okay to copy-paste the link for the series if they only have multiple seasons:
![immagine](https://user-images.githubusercontent.com/6439106/58879469-08300980-86d6-11e9-9eea-010a3ac45154.png)

but problematic if they have multiple dubs as well:
![immagine](https://user-images.githubusercontent.com/6439106/58879529-285fc880-86d6-11e9-9e94-412cc961e556.png)

**Comment by skid9000** [comment]
Well, i will see if there is an API somewhere to detect that but from what i saw last time i checked, it's a real pita :/

If there is not, i won't implement that by myself, like, parsing cr html crap (which can break at any moment depending of what cr is doing with their website) is just too much for a "non-dev" like me :/

**Comment by artaeun** [comment]
> 
> 
> Well, i will see if there is an API somewhere to detect that but from what i saw last time i checked, it's a real pita :/
> 
> If there is not, i won't implement that by myself, like, parsing cr html crap (which can break at any moment depending of what cr is doing with their website) is just too much for a "non-dev" like me :/

if i had more time up my sleeves I'd take a look myself and code it. Unfortunately that is not the case. And I sincerely have no expectations of asking anyone to do it, especially an open source software dev. I just did something from my part to provide some feedback.
On that account, thanks for all the hard work so far! It is really appreciated

**Comment by hama3254** [comment]
i don't know if this might help in this request : (written in vb.net)
[sample.txt](https://github.com/skid9000/Crunchyroll-Downloader/files/3386515/sample.txt)
![27](https://user-images.githubusercontent.com/52826614/61130542-2f3ce080-a4b7-11e9-92dd-a1f4746fbf68.png)
![26](https://user-images.githubusercontent.com/52826614/61130545-2f3ce080-a4b7-11e9-9363-77f9bb440102.png)

**Comment by skid9000** [comment]
I'm closing this, if anyone is still interested i will reopen it.
