### ISSUE TITLE
Crashing after downloading 1 or 2 videos

### ISSUE THREAD

**Issue by Ryahn** [skid9000/Crunchyroll-Downloader#44]
**Checklist**

- [X] I checked if my issue is already referenced.
- [X] I use a release version (from a tag or master branch).
- [X] Youtube-DL is up to date
- [X] I use the version of .NET Framework that is recommended or better

**Describe the bug**
After the program downloads 1 or 2 videos, it will crash right afterwards. I am not sure if its because of a large video list or not. This is the show I am trying to download https://www.crunchyroll.com/a-certain-magical-index

**To Reproduce**
1. Put in https://www.crunchyroll.com/a-certain-magical-index
2. Let it go for a download or two

**Expected behavior**
I would just expect it to download all the videos on the page

**Screenshots**
![image](https://user-images.githubusercontent.com/2089646/73382344-52817e80-4295-11ea-9d6d-5917387d91fa.png)
![image](https://user-images.githubusercontent.com/2089646/73382452-8b215800-4295-11ea-9722-ed1ed0aee93e.png)

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : Windows 10
 - Youtube-DL version (from a cmd : 2020.01.24
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : v2.0.0
 - Region of the Crunchyroll account : US
 - URL of what you tried to download : https://www.crunchyroll.com/a-certain-magical-index

**Comment by Ryahn** [comment]
When I also try to re-download dependencies, it crashes the app as well.

**Comment by skid9000** [comment]
Is the issue still a thing ?
Also Crunchyroll doesn't support SRT subtitles anymore, try switching to ASS subtitles to see if it make a difference.

**Comment by Ryahn** [comment]
Not sure what it was and I completely forgot about this issue. I since reinstalled my OS and it hasnt had problems.

**Comment by skid9000** [comment]
Ok 🤔 
I'm closing this one then, if you can reproduce, don't hesitate to comment down below.
