### ISSUE TITLE
[YT-DL] Can't download video anymore.

### ISSUE THREAD

**Issue by werewolf004** [skid9000/Crunchyroll-Downloader#49]
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**

**To Reproduce**
1. 'Login seems to be successfull'
2. 'Add video URL'
3. 'check subtitle and choose the subtitle - mkv is unchecked'

**Expected behavior**
When I clic on "Start" I get an error: Something wrong has happened while downloading the video. Please check your URL of login credentials.
For information, all is working fine few days / last weeks

**Screenshots**

**Infos (please complete the following information):**
 - OS (from a cmd : winver) : Win7 X64
 - Youtube-DL version (from a cmd : "C:\ProgramData\Crunchy-DL\youtube-dl.exe --version" 2020.03.24
 - Crunchyroll-Downloader version (click on the about button from MainWindow) : 2.1.1
 - Region of the Crunchyroll account : FR
 - URL of what you tried to download : any video

**Additional context**
![2020-04-28 18_34_22-Windows 7 x64 - VMware Workstation](https://user-images.githubusercontent.com/63142830/80513450-5c437c80-897f-11ea-8fd3-9cbb566926d6.png)

**Comment by skid9000** [comment]
Ffs, they broke youtube-dl crunchyroll extractor AGAIN.
![image](https://user-images.githubusercontent.com/26208369/80521015-96fee200-898a-11ea-99e0-c937ad95d113.png)

**Comment by skid9000** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25047

**Comment by werewolf004** [comment]
Ok, just need to wait a fix from youtube-dl

**Comment by werewolf004** [comment]
For me it's OK, I have add the fix on my fork and compiled new windows binary (working with your apps)

**Comment by skid9000** [comment]
Yep, it seems like it's going to take some time before the [PR is merged](https://github.com/ytdl-org/youtube-dl/pull/25060), so in the meantime for people who needs Crunchy-DL to be working right now :

If you are willing to take the risk of using an "experimental build" of youtube-dl you can patch the issue by downloading my youtube-dl build [here](https://github.com/skid9000/Crunchyroll-Downloader/files/4567526/youtube-dl.zip) and putting it in C:\ProgramData\Crunchy-DL.

Be aware that this is ***NOT*** a proper long term solution, if you can, please wait for the PR to be merged so you only have to update youtube-dl from Crunchy-DL.

**Comment by skid9000** [comment]
Lmao, i should shut up some times... https://github.com/ytdl-org/youtube-dl/tree/2020.05.03

Welp, now you can update youtube-dl now from the about menu in Crunchy-DL :)
