### ISSUE TITLE
can't download pn windown 10 64bit

### ISSUE THREAD

**Issue by zerobkpro** [skid9000/Crunchyroll-Downloader#51]
**Checklist**

- [x] I checked if my issue is already referenced.
- [x] I use a release version (from a tag or master branch).
- [x] Youtube-DL is up to date
- [x] I use the version of .NET Framework that is recommended or better

**Describe the bug**

![2020-10-04_152101](https://user-images.githubusercontent.com/33318271/95010659-5308bb00-0655-11eb-8c0f-12665f24df6d.png)
![2020-10-04_152119](https://user-images.githubusercontent.com/33318271/95010661-5439e800-0655-11eb-84cc-afedf3d13387.png)

**Comment by skid9000** [comment]
Duplicate #50
