### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by henkami06** [skid9000/Crunchyroll-Downloader#6]
Can you please explain the steps ( to a rookie like me ).

I tried to build it in visual studio, after that I ran the application but no window opened.

**Comment by skid9000** [comment]
https://github.com/skid9000/Crunchyroll-Downloader/wiki/How-to-use-%3F

**Comment by henkami06** [comment]
Wow, thank you very much for such beautiful explanation !!!

If you don't mind can I ask one last question - I'm in first year of
college , studying computer science and engineering. The programming taught
in class will never bring me in level to call myself a programmer - they
teach input/output, file handling, constructor, classes and objects ( c++ )
. But I can't solve real life problems with it ( there are so many api,
modules and libraries that they won't teach in class ).

So, I wanted a little guidance from you (I think you re best person now ) .
What is the best way to learn, what path must I follow. I don't know the
order for these things.

This message got quite big, you can can reply when you get time. Thanks
again.

**Comment by henkami06** [comment]
Sir , I tried the setup also but same, no window opens (nothing happens on clicking the application.
Aah, how do I give my OS details to you ?

**Comment by henkami06** [comment]
As for .NET and visual c++ both are up-to-date (on installation of both it shows a error mentioning I already have the latest version.

**Comment by henkami06** [comment]
Yes, finally worked. Placed ffmpeg.zip, login.zip and youtube-dl in "C:\ProgramData\Crunchy-DL" and it worked. Thanks skid for your time.

**Comment by renatosk** [comment]
Im having this same problem , can u help me?
