### ISSUE TITLE
Stopped working after pressing "start"

### ISSUE THREAD

**Issue by henkami06** [skid9000/Crunchyroll-Downloader#8]
Damn one after another.

Sir, what went wrong now !?

[
![capture](https://user-images.githubusercontent.com/32891595/38769365-60f0aace-401f-11e8-87f5-d740b106a53d.PNG)
](url)

**Comment by skid9000** [comment]
Did you clone the repo from developement branch ?

If it is the case, you should clone the repo from the master branch

**Comment by skid9000** [comment]
Ha no it is me ! I forgot to merge develop to master ~~ Wait a sec

**Comment by skid9000** [comment]
Alright,

Can you pull the changes ?

**Comment by henkami06** [comment]
Yep, its working good. Nice job 👍
